### PR TITLE
Upgrade requirements

### PR DESCRIPTION
**Pull request by japauliina**
## Description

Upgrade project requirements and fix a bug that occurred in tests after the upgrade.

## Context
[Refs](https://trello.com/c/EhCNgd6i/1451-backend-requirements-pakettien-p%C3%A4ivitt%C3%A4minen)

## How Has This Been Tested?

Some manual testing locally and a new test for the found bug.

### CODE REVIEW

**Review by mhieta — APPROVED** [review]
LGTM! 👍

**Review by mhieta — CHANGES_REQUESTED** [review]
Build is still failing, needs to be fixed first.

**Comment by japauliina** [comment]
@mhieta I think the issue is that Dockerized environment has Python version 3.8 and CI configuration version 3.10.

**Review by mhieta — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
